/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BehaviorLogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var BEHAVIOR_OPTIONS = [
  "argumentative",
  "defiant",
  "sarcastic",
  "withdrawn",
  "emotional",
  "playful",
  "cooperative"
];
var FEELING_OPTIONS = [
  "frustrated",
  "hurt",
  "anxious",
  "guilty",
  "overwhelmed",
  "calm",
  "patient",
  "angry",
  "sad",
  "ashamed"
];
var THOUGHT_OPTIONS = [
  "She's pushing my buttons",
  "I'm losing control",
  "I'm a bad mom",
  "She doesn't care what I think",
  "This will never get better",
  "I need to fix this now"
];
var REACTION_OPTIONS = [
  "I reacted emotionally (e.g., raised voice, shut down, lectured)",
  "I responded calmly (e.g., paused, set a boundary, walked away)",
  "Not sure / mixed"
];
var BehaviorLogPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("clipboard-list", "Log Interaction", () => {
      new BehaviorLogModal(this.app).open();
    });
    this.addCommand({
      id: "log-behavior",
      name: "Log Interaction",
      callback: () => {
        new BehaviorLogModal(this.app).open();
      }
    });
  }
};
var BehaviorLogModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
    this.state = {
      timestamp: new Date(),
      whatHappened: "",
      directQuotes: [],
      currentQuote: "",
      behaviors: [],
      customBehavior: "",
      possibleTrigger: "",
      feelings: [],
      customFeeling: "",
      customFeelingIntensity: "medium",
      thoughts: [],
      customThought: "",
      reactions: [],
      customReaction: ""
    };
  }
  onOpen() {
    this.renderForm();
  }
  onClose() {
    this.contentEl.empty();
  }
  renderForm(preserveScroll = false) {
    const { contentEl } = this;
    const scrollArea = contentEl.querySelector(".behavior-log-scroll");
    const scrollTop = (scrollArea == null ? void 0 : scrollArea.scrollTop) || 0;
    contentEl.empty();
    contentEl.addClass("behavior-log-modal");
    const container = contentEl.createDiv({ cls: "behavior-log-container" });
    container.createEl("h2", { text: "Log Interaction", cls: "behavior-log-header" });
    const newScrollArea = container.createDiv({ cls: "behavior-log-scroll" });
    this.renderWhatHappened(newScrollArea);
    this.renderBehaviors(newScrollArea);
    this.renderFeelings(newScrollArea);
    this.renderThoughts(newScrollArea);
    this.renderReactions(newScrollArea);
    const submitDiv = container.createDiv({ cls: "behavior-log-submit" });
    const submitBtn = submitDiv.createEl("button", {
      text: "Save Entry",
      cls: "mod-cta behavior-log-submit-btn"
    });
    submitBtn.addEventListener("click", () => this.submitLog());
    if (preserveScroll && scrollTop > 0) {
      requestAnimationFrame(() => {
        newScrollArea.scrollTop = scrollTop;
      });
    }
  }
  // Section 1: What happened?
  renderWhatHappened(container) {
    const section = container.createDiv({ cls: "behavior-log-section" });
    section.createEl("h3", { text: "What happened?" });
    section.createEl("p", { text: 'Factual context \u2014 the "what"', cls: "section-subtitle" });
    const textarea = section.createEl("textarea", {
      cls: "behavior-log-textarea",
      attr: {
        placeholder: 'One or two sentences: Where were you? What started the interaction? (e.g., "Asking her to clean her room," "She came home 20 mins late.")'
      }
    });
    textarea.value = this.state.whatHappened;
    textarea.addEventListener("input", (e) => {
      this.state.whatHappened = e.target.value;
    });
    section.createEl("h4", { text: "Direct Quotes", cls: "subsection-title" });
    section.createEl("p", { text: "Add specific words or phrases she said (optional)", cls: "quote-hint" });
    if (this.state.directQuotes.length > 0) {
      const quotesContainer = section.createDiv({ cls: "quotes-bubbles" });
      this.state.directQuotes.forEach((quote, idx) => {
        const bubble = quotesContainer.createDiv({ cls: "quote-bubble" });
        bubble.createSpan({ text: `"${quote}"` });
        const removeBtn = bubble.createEl("button", { text: "\xD7", cls: "remove-quote-btn" });
        removeBtn.addEventListener("click", () => {
          this.state.directQuotes.splice(idx, 1);
          this.renderForm(true);
        });
      });
    }
    const quoteInputRow = section.createDiv({ cls: "custom-input-row" });
    const quoteInput = quoteInputRow.createEl("input", {
      type: "text",
      cls: "custom-input",
      attr: { placeholder: "Type a quote and press Add..." }
    });
    quoteInput.value = this.state.currentQuote;
    quoteInput.addEventListener("input", (e) => {
      this.state.currentQuote = e.target.value;
    });
    quoteInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && this.state.currentQuote.trim()) {
        e.preventDefault();
        this.state.directQuotes.push(this.state.currentQuote.trim());
        this.state.currentQuote = "";
        this.renderForm(true);
      }
    });
    const addQuoteBtn = quoteInputRow.createEl("button", { text: "Add", cls: "add-custom-btn" });
    addQuoteBtn.addEventListener("click", () => {
      if (this.state.currentQuote.trim()) {
        this.state.directQuotes.push(this.state.currentQuote.trim());
        this.state.currentQuote = "";
        this.renderForm(true);
      }
    });
  }
  // Section 2: How was she acting?
  renderBehaviors(container) {
    const section = container.createDiv({ cls: "behavior-log-section" });
    section.createEl("h3", { text: "How was she acting?" });
    section.createEl("p", {
      text: 'Observable behavior \u2014 no interpretation. Avoid "disrespectful" or "manipulative."',
      cls: "section-subtitle"
    });
    const chipsContainer = section.createDiv({ cls: "chips-container" });
    BEHAVIOR_OPTIONS.forEach((behavior) => {
      const chip = chipsContainer.createEl("button", {
        text: behavior,
        cls: `chip ${this.state.behaviors.includes(behavior) ? "selected" : ""}`
      });
      chip.addEventListener("click", () => {
        this.toggleArrayItem(this.state.behaviors, behavior);
        this.renderForm(true);
      });
    });
    const customRow = section.createDiv({ cls: "custom-input-row" });
    const customInput = customRow.createEl("input", {
      type: "text",
      cls: "custom-input",
      attr: { placeholder: "Add custom behavior..." }
    });
    customInput.value = this.state.customBehavior;
    customInput.addEventListener("input", (e) => {
      this.state.customBehavior = e.target.value;
    });
    const addBtn = customRow.createEl("button", { text: "+", cls: "add-custom-btn" });
    addBtn.addEventListener("click", () => {
      if (this.state.customBehavior.trim()) {
        this.state.behaviors.push(this.state.customBehavior.trim());
        this.state.customBehavior = "";
        this.renderForm(true);
      }
    });
    this.renderCustomChips(section, this.state.behaviors, BEHAVIOR_OPTIONS);
    section.createEl("h4", { text: "Possible Trigger (if known)", cls: "subsection-title" });
    const triggerTextarea = section.createEl("textarea", {
      cls: "behavior-log-textarea",
      attr: {
        placeholder: "What might have triggered this behavior? (optional)"
      }
    });
    triggerTextarea.value = this.state.possibleTrigger;
    triggerTextarea.addEventListener("input", (e) => {
      this.state.possibleTrigger = e.target.value;
    });
  }
  // Section 3: How was I feeling?
  renderFeelings(container) {
    const section = container.createDiv({ cls: "behavior-log-section" });
    section.createEl("h3", { text: "How was I feeling?" });
    section.createEl("p", { text: "Emotional self-check \u2014 builds awareness", cls: "section-subtitle" });
    const chipsContainer = section.createDiv({ cls: "chips-container" });
    FEELING_OPTIONS.forEach((feeling) => {
      const existing = this.state.feelings.find((f) => f.feeling === feeling);
      const chip = chipsContainer.createEl("button", {
        text: feeling,
        cls: `chip ${existing ? "selected" : ""}`
      });
      chip.addEventListener("click", () => {
        if (existing) {
          this.state.feelings = this.state.feelings.filter((f) => f.feeling !== feeling);
        } else {
          this.state.feelings.push({ feeling, intensity: "medium" });
        }
        this.renderForm(true);
      });
    });
    const customRow = section.createDiv({ cls: "custom-input-row" });
    const customInput = customRow.createEl("input", {
      type: "text",
      cls: "custom-input",
      attr: { placeholder: "Add custom feeling..." }
    });
    customInput.value = this.state.customFeeling;
    customInput.addEventListener("input", (e) => {
      this.state.customFeeling = e.target.value;
    });
    const addBtn = customRow.createEl("button", { text: "+", cls: "add-custom-btn" });
    addBtn.addEventListener("click", () => {
      if (this.state.customFeeling.trim()) {
        this.state.feelings.push({
          feeling: this.state.customFeeling.trim(),
          intensity: this.state.customFeelingIntensity
        });
        this.state.customFeeling = "";
        this.renderForm(true);
      }
    });
    if (this.state.feelings.length > 0) {
      const intensitySection = section.createDiv({ cls: "intensity-section" });
      intensitySection.createEl("h4", { text: "Intensity Level" });
      this.state.feelings.forEach((f, idx) => {
        const row = intensitySection.createDiv({ cls: "intensity-row" });
        row.createEl("span", { text: f.feeling, cls: "intensity-label" });
        const intensityBtns = row.createDiv({ cls: "intensity-buttons" });
        ["low", "medium", "high"].forEach((level) => {
          const btn = intensityBtns.createEl("button", {
            text: level.charAt(0).toUpperCase() + level.slice(1),
            cls: `intensity-btn ${level} ${f.intensity === level ? "selected" : ""}`
          });
          btn.addEventListener("click", () => {
            this.state.feelings[idx].intensity = level;
            this.renderForm(true);
          });
        });
        const removeBtn = row.createEl("button", { text: "\xD7", cls: "remove-feeling-btn" });
        removeBtn.addEventListener("click", () => {
          this.state.feelings.splice(idx, 1);
          this.renderForm(true);
        });
      });
    }
  }
  // Section 4: What was I thinking?
  renderThoughts(container) {
    const section = container.createDiv({ cls: "behavior-log-section" });
    section.createEl("h3", { text: "What was I thinking?" });
    section.createEl("p", { text: "Automatic thoughts \u2014 reveals cognitive patterns", cls: "section-subtitle" });
    const checkboxContainer = section.createDiv({ cls: "checkbox-list" });
    THOUGHT_OPTIONS.forEach((thought) => {
      const row = checkboxContainer.createDiv({ cls: "checkbox-row" });
      const checkbox = row.createEl("input", {
        type: "checkbox",
        cls: "thought-checkbox"
      });
      checkbox.checked = this.state.thoughts.includes(thought);
      checkbox.addEventListener("change", () => {
        this.toggleArrayItem(this.state.thoughts, thought);
      });
      row.createEl("label", { text: `"${thought}"`, cls: "checkbox-label" });
    });
    const customRow = section.createDiv({ cls: "custom-input-row" });
    const customInput = customRow.createEl("input", {
      type: "text",
      cls: "custom-input",
      attr: { placeholder: "Add custom thought..." }
    });
    customInput.value = this.state.customThought;
    customInput.addEventListener("input", (e) => {
      this.state.customThought = e.target.value;
    });
    const addBtn = customRow.createEl("button", { text: "+", cls: "add-custom-btn" });
    addBtn.addEventListener("click", () => {
      if (this.state.customThought.trim()) {
        this.state.thoughts.push(this.state.customThought.trim());
        this.state.customThought = "";
        this.renderForm(true);
      }
    });
    this.renderCustomChips(section, this.state.thoughts, THOUGHT_OPTIONS);
  }
  // Section 5: Did I react or respond?
  renderReactions(container) {
    const section = container.createDiv({ cls: "behavior-log-section" });
    section.createEl("h3", { text: "Did I react or respond?" });
    section.createEl("p", {
      text: "Gently builds awareness of reactivity without judgment",
      cls: "section-subtitle"
    });
    const checkboxContainer = section.createDiv({ cls: "checkbox-list" });
    REACTION_OPTIONS.forEach((reaction) => {
      const row = checkboxContainer.createDiv({ cls: "checkbox-row" });
      const checkbox = row.createEl("input", {
        type: "checkbox",
        cls: "thought-checkbox"
      });
      checkbox.checked = this.state.reactions.includes(reaction);
      checkbox.addEventListener("change", () => {
        this.toggleArrayItem(this.state.reactions, reaction);
      });
      row.createEl("label", { text: reaction, cls: "checkbox-label" });
    });
    const customRow = section.createDiv({ cls: "custom-input-row" });
    const customInput = customRow.createEl("input", {
      type: "text",
      cls: "custom-input",
      attr: { placeholder: "Add custom reaction..." }
    });
    customInput.value = this.state.customReaction;
    customInput.addEventListener("input", (e) => {
      this.state.customReaction = e.target.value;
    });
    const addBtn = customRow.createEl("button", { text: "+", cls: "add-custom-btn" });
    addBtn.addEventListener("click", () => {
      if (this.state.customReaction.trim()) {
        this.state.reactions.push(this.state.customReaction.trim());
        this.state.customReaction = "";
        this.renderForm(true);
      }
    });
    this.renderCustomChips(section, this.state.reactions, REACTION_OPTIONS);
  }
  // Helper: Render custom chips (items not in presets)
  renderCustomChips(container, items, presets) {
    const customItems = items.filter((item) => !presets.includes(item));
    if (customItems.length > 0) {
      const customChipsDiv = container.createDiv({ cls: "custom-chips" });
      customItems.forEach((item) => {
        const chip = customChipsDiv.createDiv({ cls: "custom-chip" });
        chip.createSpan({ text: item });
        const removeBtn = chip.createEl("button", { text: "\xD7", cls: "remove-chip-btn" });
        removeBtn.addEventListener("click", () => {
          const idx = items.indexOf(item);
          if (idx > -1)
            items.splice(idx, 1);
          this.renderForm(true);
        });
      });
    }
  }
  // Helper: Toggle item in array
  toggleArrayItem(arr, item) {
    const idx = arr.indexOf(item);
    if (idx > -1) {
      arr.splice(idx, 1);
    } else {
      arr.push(item);
    }
  }
  // Submit the log
  async submitLog() {
    const dateStr = this.formatDate(this.state.timestamp);
    const feelingsStr = this.state.feelings.map((f) => `${f.feeling} (${f.intensity})`).join(", ") || "None selected";
    const behaviorsStr = this.state.behaviors.join(", ") || "None selected";
    const thoughtsStr = this.state.thoughts.map((t) => `"${t}"`).join(", ") || "None selected";
    const reactionsStr = this.state.reactions.join(", ") || "None selected";
    const whatHappened = this.escapeMarkdown(this.state.whatHappened) || "Not provided";
    const directQuotes = this.state.directQuotes.length > 0 ? this.state.directQuotes.map((q) => `"${this.escapeMarkdown(q)}"`).join(", ") : "";
    const possibleTrigger = this.escapeMarkdown(this.state.possibleTrigger) || "";
    const logEntry = `
> [!NOTE]+ ${dateStr}
> 
> **What happened?**
> ${whatHappened}
>${directQuotes ? `
> **Direct Quotes:** ${directQuotes}
>` : ""}
> 
> **How was she acting?**
> ${behaviorsStr}
>${possibleTrigger ? `
> **Possible Trigger:** ${possibleTrigger}
>` : ""}
> 
> **How was I feeling?**
> ${feelingsStr}
> 
> **What was I thinking?**
> ${thoughtsStr}
> 
> **Did I react or respond?**
> ${reactionsStr}

---

`;
    const targetFile = "Behavior Log.md";
    const fileObj = this.app.vault.getAbstractFileByPath(targetFile);
    if (fileObj instanceof import_obsidian.TFile) {
      await this.app.vault.append(fileObj, logEntry);
    } else {
      await this.app.vault.create(targetFile, `# Behavior Log

Track patterns and build self-awareness.

---
${logEntry}`);
    }
    new import_obsidian.Notice("Entry saved successfully!");
    this.close();
  }
  formatDate(date) {
    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, "0");
    const dd = String(date.getDate()).padStart(2, "0");
    const hh = String(date.getHours()).padStart(2, "0");
    const min = String(date.getMinutes()).padStart(2, "0");
    return `${yyyy}-${mm}-${dd} ${hh}:${min}`;
  }
  escapeMarkdown(text) {
    return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
  }
};
